const transliteRule = [
  {ua: "Аа", en: "Aa", position: "", exampleUK: "Алушта Андрій", exampleEN: "Alushta Andrii"},
  {ua: "Бб", en: "Bb", position: "", exampleUK: "Борщагівка Борисенко", exampleEN: "Borshchahivka Borysenko"},
  {ua: "Вв", en: "Vv", position: "", exampleUK: "Вінниця Володимир", exampleEN: "Vinnytsia Volodymyr"},
  {ua: "Гг", en: "Hh", position: "", exampleUK: "Гадяч Богдан Згурський", exampleEN: "Hadiach Bohdan Zghurskyi"},
  {ua: "Ґґ", en: "Gg", position: "", exampleUK: "Ґалаґан Ґорґани", exampleEN: "Galagan Gorgany"},
  {ua: "Дд", en: "Dd", position: "", exampleUK: "Донецьк Дмитро", exampleEN: "Donetsk Dmytro"},
  {ua: "Ее", en: "Ee", position: "", exampleUK: "Рівне Олег Есмань", exampleEN: "Rivne Oleh Esman"},
  {ua: "Єє", en: "Ye", position: "ie", exampleUK: "Єнакієве Гаєвич Короп'є", exampleEN: "Yenakiieve Haievych Koropie"},
  {ua: "Жж", en: "Zh", position: "", exampleUK: "Житомир Жанна Жежелів", exampleEN: "Zhytomyr Zhanna Zhezheliv"},
  {ua: "Зз", en: "Zz", position: "", exampleUK: "Закарпаття Казимирчук", exampleEN: "Zakarpattia Kazymyrchuk"},
  {ua: "Ии", en: "Yy", position: "", exampleUK: "Медвин Михайленко", exampleEN: "Medvyn Mykhailenko"},
  {ua: "Іі", en: "Ii", position: "", exampleUK: "Іванків Іващенко", exampleEN: "Ivankiv Ivashchenko"},
  {ua: "Її", en: "Yi", position: "i", exampleUK: "Їжакевич Кадиївка Мар'їне", exampleEN: "Yizhakevych Kadyivka Marine"},
  {ua: "Йй", en: "Y", position: "i", exampleUK: "Йосипівка Стрий Олексій", exampleEN: "Yosypivka Stryi Oleksii"},
  {ua: "Кк", en: "Kk", position: "", exampleUK: "Київ Коваленко", exampleEN: "Kyiv Kovalenko"},
  {ua: "Лл", en: "Ll", position: "", exampleUK: "Лебедин Леонід", exampleEN: "Lebedyn Leonid"},
  {ua: "Мм", en: "Mm", position: "", exampleUK: "Миколаїв Маринич", exampleEN: "Mykolaiv Marynych"},
  {ua: "Нн", en: "Nn", position: "", exampleUK: "Ніжин Наталія", exampleEN: "Nizhyn Nataliia"},
  {ua: "Оо", en: "Oo", position: "", exampleUK: "Одеса Онищенко", exampleEN: "Odesa Onyshchenko"},
  {ua: "Пп", en: "Pp", position: "", exampleUK: "Полтава Петро", exampleEN: "Poltava Petro"},
  {ua: "Рр", en: "Rr", position: "", exampleUK: "Решетилівка Рибчинський", exampleEN: "Reshetylivka Rybchynskyi"},
  {ua: "Сс", en: "Ss", position: "", exampleUK: "Суми Соломія", exampleEN: "Sumy Solomiia"},
  {ua: "Тт", en: "Tt", position: "", exampleUK: "Тернопіль Троць", exampleEN: "Ternopil Trots"},
  {ua: "Уу", en: "Uu", position: "", exampleUK: "Ужгород Уляна", exampleEN: "Uzhhorod Uliana"},
  {ua: "Фф", en: "Ff", position: "", exampleUK: "Фастів Філіпчук", exampleEN: "Fastiv Filipchuk"},
  {ua: "Хх", en: "Kh", position: "", exampleUK: "Харків Христина", exampleEN: "Kharkiv Khrystyna"},
  {ua: "Цц", en: "Ts", position: "", exampleUK: "Біла Церква Стеценко", exampleEN: "Bila Tserkva Stetsenko"},
  {ua: "Чч", en: "Ch", position: "", exampleUK: "Чернівці Шевченко", exampleEN: "Chernivtsi Shevchenko"},
  {ua: "Шш", en: "Sh", position: "", exampleUK: "Шостка Кишеньки", exampleEN: "Shostka Kyshenky"},
  {ua: "Щщ", en: "Shch", position: "", exampleUK: "Щербухи Гоща Гаращенко", exampleEN: "Shcherbukhy Hoshcha Harashchenko"},
  {ua: "Юю", en: "Yu", position: "iu", exampleUK: "Юрій Корюківка", exampleEN: "Yurii Koriukivka"},
  {ua: "Яя", en: "Ya", position: "ia", exampleUK: "Яготин Ярошенко Костянтин Знам'янка Феодосія", exampleEN: "Yahotyn Yaroshenko Kostiantyn Znamianka Feodosiia"},
]

export { transliteRule }